apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # POSTGRES_PASSWORD: cGFzc3dvcmQ=       # "password"
  POSTGRES_DB: bXJlYWxkYg==        # "postgres"
  PGADMIN_PASSWORD: MTIzNA==        # "1234"
